export const PLANS = [
  {
    name: "Free",
    price: "¥0",
    period: "永久無料",
    description: "まずは無料で競合価格の監視を始めましょう",
    gradient: "from-slate-500 to-zinc-600",
    shadowColor: "shadow-slate-500/10",
    borderColor: "border-border/50",
    features: [
      { text: "監視商品数 3件", included: true },
      { text: "競合URL 2件/商品", included: true },
      { text: "ダッシュボード", included: true },
      { text: "価格アラート", included: true },
      { text: "価格履歴 7日間", included: true },
      { text: "無制限の商品登録", included: false },
      { text: "無制限の競合URL", included: false },
      { text: "無制限の価格履歴", included: false },
    ],
    cta: "無料で始める",
    ctaVariant: "outline",
    highlight: false,
  },
  {
    name: "Pro",
    price: "¥1,980",
    period: "/月",
    description: "本格的な競合分析で価格戦略を最適化",
    gradient: "from-emerald-500 to-cyan-500",
    shadowColor: "shadow-emerald-500/20",
    borderColor: "border-emerald-500/30",
    features: [
      { text: "監視商品数 50件", included: true },
      { text: "競合URL 10件/商品", included: true },
      { text: "ダッシュボード", included: true },
      { text: "価格アラート", included: true },
      { text: "価格履歴 無制限", included: true },
      { text: "優先サポート", included: true },
    ],
    cta: "Proを始める",
    ctaVariant: "default",
    highlight: true,
  },
];
